/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Primary palette (dynamic via CSS variables)
        primary: 'var(--color-primary-light)',
        'primary-dim': 'var(--color-primary-dim-light)',
        'primary-container': 'var(--color-primary-container-light)',
        'on-primary': 'var(--color-on-primary-light)',
        'on-primary-container': 'var(--color-on-primary-container-light)',
        'primary-fixed': 'var(--color-primary-fixed-light)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim-light)',
        'on-primary-fixed': '#000569',
        'on-primary-fixed-variant': '#0015e6',
        'inverse-primary': '#bec2ff',
        // Secondary palette
        secondary: '#973593',
        'secondary-container': '#fd8ef2',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#7b1979',
        'secondary-fixed': '#ffd7f5',
        'secondary-fixed-dim': '#ffabf3',
        'on-secondary-fixed': '#380038',
        'on-secondary-fixed-variant': '#7b1879',
        // Tertiary palette
        tertiary: '#735c00',
        'tertiary-container': '#cda71e',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#4e3d00',
        'tertiary-fixed': '#ffe086',
        'tertiary-fixed-dim': '#ebc23b',
        'on-tertiary-fixed': '#231a00',
        'on-tertiary-fixed-variant': '#574500',
        // Surface palette
        surface: '#fcf8ff',
        'surface-dim': '#dcd8e2',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f2fc',
        'surface-container': '#f0ecf6',
        'surface-container-high': '#eae7f0',
        'surface-container-highest': '#e5e1ea',
        'surface-variant': '#e5e1ea',
        'surface-tint': '#2f3eff',
        'on-surface': '#1b1b22',
        'on-surface-variant': '#464552',
        'inverse-surface': '#303037',
        'inverse-on-surface': '#f3eff9',
        // Background
        background: '#fcf8ff',
        'on-background': '#1b1b22',
        // Outline
        outline: '#777584',
        'outline-variant': '#c8c4d4',
        // Error
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        // Dark mode overrides
        'dark-surface': '#12121a',
        'dark-surface-container': '#1e1e2a',
        'dark-surface-container-high': '#252533',
        'dark-on-surface': '#e5e1ea',
        'dark-on-surface-variant': '#c8c4d4',
        'dark-outline': '#918fa0',
        'dark-outline-variant': '#464552',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        headline: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Consolas', 'monospace'],
      },
      fontSize: {
        'display': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.0', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      spacing: {
        'xs': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '24px',
        'margin': '24px',
        'base': '4px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      boxShadow: {
        'hard': '4px 4px 0px 0px #1b1b22',
        'hard-sm': '2px 2px 0px 0px #1b1b22',
        'hard-lg': '8px 8px 0px 0px #1b1b22',
        'hard-violet': '4px 4px 0px 0px #918efa',
        'hard-cyan': '4px 4px 0px 0px #06b6d4',
        'hard-lime': '4px 4px 0px 0px #84cc16',
        'hard-yellow': '4px 4px 0px 0px #eab308',
        'hard-red': '4px 4px 0px 0px #fa7a7a',
        'card-violet': '6px 6px 0px 0px #918efa',
        'card-cyan': '6px 6px 0px 0px #06b6d4',
        'card-lime': '6px 6px 0px 0px #84cc16',
        'card-yellow': '6px 6px 0px 0px #eab308',
        // Dark mode
        'hard-dark': '4px 4px 0px 0px #e5e1ea',
        'hard-sm-dark': '2px 2px 0px 0px #e5e1ea',
      },
      animation: {
        'marquee': 'marquee 20s linear infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'slide-in-right': 'slideInRight 200ms ease-out',
        'slide-in-bottom': 'slideInBottom 200ms ease-out',
        'fade-in': 'fadeIn 150ms ease-out',
        'pop': 'pop 200ms ease-out',
        'spin-slow': 'spin 3s linear infinite',
        'pulse-dot': 'pulseDot 2s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInBottom: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        pop: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pulseDot: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.4' },
        },
      },
    },
  },
  plugins: [],
};
